human-detector/human-detector

server/backend/src/app.module.ts
server/backend/src/cameras/camera.entity.ts
server/backend/src/cameras/cameras.controller.spec.ts
server/backend/src/cameras/cameras.service.spec.ts
server/backend/test/cameras.e2e-spec.ts
server/backend/test/steps/send-notification.steps.ts

Some formatting issues were floating around because I was running straight Vim with no formatter before. The changes are minimal, but I figured I would rather have this in a separate PR rather than clutter the PRs I'll send out for the backend implementation.
`npm run test` and `npm run lint`. There's still some unused variables, but most of those are from missing implementations and mocks that I plan on replacing later.

backend: Fix formatting

---

server/backend/src/cameras/camera.entity.ts
server/backend/src/cameras/notification.entity.ts
server/backend/src/util/index.ts
server/backend/src/util/timestamp.type.ts
server/backend/test/helpers/test-stack.ts
server/backend/test/steps/list-camera-groups.steps.ts
server/backend/test/steps/send-notification.steps.ts

The backend's feature tests are full integration tests, so they spawn dependencies in Docker containers. This PR adds a helper for spawning the full stack and refactors the current set of feature tests to use this helper.
This helped the previously broken suite of tests for the `send-notification` feature to run again, but MikroORM had some issues with that and wasted my entire weekend. At least they work now though :)
`npm test`

Add a helper for spawning a test stack

---

server/backend/src/users/user.entity.ts
server/backend/src/users/users.controller.ts
server/backend/src/users/users.service.ts
server/backend/test/features/update-push-token.feature
server/backend/test/steps/update-push-token.steps.ts

This implements the `/users/:id/notifyToken` endpoint needed by the mobile app for notification delivery.
`npm test` (auth tests are failing, no Keycloak yet :sob:)

[EYE-51] Add endpoint for updating notification token

---

.gitignore
README.md
server/backend/.dockerignore
server/backend/Dockerfile
server/backend/src/users/user.entity.ts
server/database/init/01-create.sql
server/docker-compose.yaml
server/keycloak/Dockerfile
server/keycloak/data/import/user-realm.json
server/keycloak/sync-users-spi/pom.xml
server/keycloak/sync-users-spi/src/main/java/org/eyespy/keycloak/provider/ConfigProvider.java
server/keycloak/sync-users-spi/src/main/java/org/eyespy/keycloak/provider/EnvironmentConfigProvider.java
server/keycloak/sync-users-spi/src/main/java/org/eyespy/keycloak/provider/PostgresqlUserStoreProvider.java
server/keycloak/sync-users-spi/src/main/java/org/eyespy/keycloak/provider/SyncUsersProvider.java
server/keycloak/sync-users-spi/src/main/java/org/eyespy/keycloak/provider/SyncUsersProviderFactory.java
server/keycloak/sync-users-spi/src/main/java/org/eyespy/keycloak/provider/UserStoreProvider.java
server/keycloak/sync-users-spi/src/main/resources/META-INF/services/org.keycloak.events.EventListenerProviderFactory

When a user registers through Keycloak, they are persisted in Keycloak's configured database, which isn't accessible from our Nest application. This leaves us with two options:
1. Point our Nest application and Keycloak at the same database
2. Synchronize users between our Keycloak and Nest databases
I thought option 2 would give us more flexibility when changing our user schemas (we won't have to worry about everything else Keycloak wants to store as well), and it would be simpler to set up the two if they just create different schemas in different databases. Keycloak seems to want it's own database, so I'll let it have one.
TODO before it's ready for review:
No unit tests exist because I had enough trouble and wasted enough time trying to get the thing to work properly. I set up a …

[EYE-43] Keycloak User Sync Plugin

---

app/human-detector-app/App.tsx
app/human-detector-app/__tests__/BackendService.test.ts
app/human-detector-app/__tests__/notifTokenInit.test.ts
app/human-detector-app/services/backendService.ts
app/human-detector-app/src/notifications/notifTokenInit.ts

This PR has changes so that the user will use the authorization header when sending an expo notification token.
** Other endpoints will have these changes in a separate PR.  We are just focusing on notifications to prepare for demo **
Local testing showed that we had the function passing the access token to the http request.
All other tests have been changed to include the access token parameter and pass for both sendNotifyTokenAPI and notif token init functions.

Dev for access token mobile app

---

server/backend/src/cameras/cameras.controller.spec.ts
server/backend/src/cameras/cameras.controller.ts

We need a heartbeat endpoint so the camera won't die. We should probably talk later about whether we should keep it or add the feature to the app, but we need it for demo so here's a stub.
- `npm test`

backend: Add stub heartbeat endpoint

---

server/backend/test/features/list-camera-groups.feature
server/backend/test/helpers/keycloak-container.ts
server/backend/test/steps/__snapshots__/list-camera-groups.steps.ts.snap
server/backend/test/steps/list-camera-groups.steps.ts

In my pre-demo panic, I forgot to adjust the list-camera-group tests to work with user authorization. This PR fixes that.
`npm test`. When combined with #31, all of our backend integration tests will be passing :partying_face:

backend: Fix remaining user auth tests

---

.github/workflows/main.yml
server/docker-compose.yaml

The backend integration tests depend on some containers being built before running, so we need to update our workflow.

Fix backend CI

---

server/backend/package-lock.json
server/backend/package.json
server/backend/src/cameras/camera-auth.guard.spec.ts
server/backend/src/cameras/camera-auth.guard.ts
server/backend/src/cameras/camera.entity.ts
server/backend/src/cameras/cameras.controller.spec.ts
server/backend/src/cameras/cameras.controller.ts
server/backend/src/cameras/cameras.module.ts
server/backend/src/cameras/cameras.service.spec.ts
server/backend/src/cameras/cameras.service.ts
server/backend/src/util/bytes.ts
server/backend/src/util/index.ts
server/backend/test/features/send-notification.feature
server/backend/test/helpers/camera.ts
server/backend/test/helpers/execution-context.ts
server/backend/test/steps/send-notification.steps.ts

Now cameras are required to present their token when calling camera endpoints (heartbeat, send notification). No more spamming Matt's phone :(
- `npm test` - some tests had to be reworked so MikroORM would play nicely with Jest

[EYE-43] Camera authorization

---

.github/workflows/main.yml
README.md
server/backend/README.md
server/backend/test/helpers/test-stack.ts

Docker seems to have changed image naming conventions for Compose between v1 and v2 ([source](https://stackoverflow.com/a/69519102)), breaking our backend tests on Compose v2. Rather than throwing compatibility flags everywhere to support my dusty old Docker Compose v1 install, I figured it would be best to require v2.
- `npm test` still works after removing old `server_*` containers and rebuilding with `docker compose build`
- The backend workflow still appears to be [successfully failing](https://github.com/tucker-moore/human-detector/actions/runs/3304816739/jobs/5454490816) (no issues related to Compose)

backend: Require Docker Compose v2

---

.github/workflows/main.yml
app/human-detector-app/App.tsx
app/human-detector-app/__tests__/BackendService.test.ts
app/human-detector-app/__tests__/Camera.test.ts
app/human-detector-app/__tests__/Group.test.ts
app/human-detector-app/__tests__/User.test.ts
app/human-detector-app/__tests__/__features__/__feature-tests__/PushNotification.steps.ts
app/human-detector-app/__tests__/notifTokenInit.test.ts
app/human-detector-app/classes/Camera.tsx
app/human-detector-app/classes/Group.tsx
app/human-detector-app/classes/User.tsx
app/human-detector-app/components/CameraSettingsButton.tsx
app/human-detector-app/components/KeyCloakButton.tsx
app/human-detector-app/package-lock.json
app/human-detector-app/package.json
app/human-detector-app/screens/CameraScreen.tsx
app/human-detector-app/screens/GroupScreen.tsx
app/human-detector-app/screens/LoginScreen.tsx
app/human-detector-app/screens/NotifScreen.tsx
app/human-detector-app/screens/SettingsScreen.tsx
app/human-detector-app/services/backendService.ts

I noticed a few (hundred) linter errors when I started looking at the mobile app, so I cleaned them all up and added a job to enforce linter checks because I'm evil.
- `npm run lint` reports 9 warnings and 0 errors. If you run this on `main`, you'll get about 100 errors.
- Tests previously passing with `npm test` still pass

Add app lint checks to CI

---

app/human-detector-app/screens/CameraRegistration/BluetoothScreen.tsx
app/human-detector-app/screens/LoginScreen.tsx
app/human-detector-app/src/styles.ts

This PR deals with changing how the styling looks in the `BluetoothScreen` for registering a new camera.
- Added text that tells the user what is supposed to be happening on this screen.
- Then adds X-number of `TouchableOpacities` for how many cameras it detects and a value given by `getTitle(device)`
Includes changes that Avery sent over, so make sure that those changes line up and verify that the changes look just like the image below since an Emulated Android cannot do Bluetooth. It won't look exactly like below, just verify that styling-wise everything matches up.

Bluetooth Screen styling.

---

app/human-detector-app/App.tsx
app/human-detector-app/classes/Notification.ts
app/human-detector-app/classes/PushNotificationData.ts
server/backend/src/cameras/cameras.service.ts

This PR synchronizes the app's notification list using received push notifications, as well as redirecting to a notification's associated snapshot upon tapping the notification.
TODOs:
- Use [this](https://pastebin.com/zuDZQESR) data (pw `senioritis`) in the [Push Notification Tool](https://expo.dev/notifications) while logged in as the test user. You should receive a new notification for the `awnaw` camera in `the group`

[EYE-78] Push notification updates, redirects

---

app/human-detector-app/App.tsx
app/human-detector-app/package-lock.json
app/human-detector-app/package.json
app/human-detector-app/screens/NotifScreen.tsx

The notification timestamps looked pretty ugly before because they were ISO strings. Now, they print a shortened date with a locale timezone aware time with AM or PM.

Prettier notification timestamp formatting

---

app/human-detector-app/screens/CameraRegistration/BluetoothScreen.tsx
app/human-detector-app/src/ble/bleServices.ts
app/human-detector-app/src/ble/helpers.ts

This PR fixes bugs EYE-102, EYE-104, EYE-109 and EYE-120.  I'll explain all of these below.
[EYE-120](https://eyespycamera.atlassian.net/jira/software/projects/EYE/boards/1?selectedIssue=EYE-120) and [EYE-102](https://eyespycamera.atlassian.net/jira/software/projects/EYE/boards/1?selectedIssue=EYE-102) were both fixed by the same changes.
These changes include changes to the `useFocusEffect` in the BluetoothScreen.  The hook `useFocusEffect()` would call its cleanup function on every re render of the app.  In other words, every time there is a new device and the app has to re render the list, the cleanup function with `stopScanForDevices()` will be run.  To fix this, I just wrapped the contents of the original `useFocusEffect` in `React.useCallback()` so the effect doesn't have to be …

[EYE-104] Bluetooth scanning error handling and stop scanning fix

---

app/human-detector-app/eas.json

Made it so when making an EAS build, instead of a `.aab` file, it will generate a `.apk` file on build.  
This is made to prepare for mobile app deployment for next sprint.

Changed EAS Production Settings

---

app/human-detector-app/App.tsx
app/human-detector-app/__tests__/BackendService.test.ts
app/human-detector-app/classes/Group.tsx
app/human-detector-app/classes/Notification.ts
app/human-detector-app/classes/PushNotificationData.ts
app/human-detector-app/classes/User.tsx
app/human-detector-app/screens/CameraRegistration/EnterCameraRegInfoScreen.tsx
app/human-detector-app/screens/NotifScreen.tsx
app/human-detector-app/services/backendService.ts
app/human-detector-app/src/styles.ts

This PR revamps the notification screen to look better.  This involves restyling the menu items on the notification screen. 
This also makes it so that the camera name pops up on the notification.  This is mainly for the all notifications screen where the user won't know what camera a notification is in until the user clicks on it.
I don't really like how I have it set up right now (and I'm not sure how I'm going to test the post notification stuff since my phone doesn't work with notifications as for as we've tested???).  Therefore, most of the changes that I have done with zod and type inference I have no way to confirm or deny if its working right now. 
On my other changes, I added `groupId` and `cameraId` to the Notification class so that from the notification screen, we can get the …

[EYE-124] Notification screen revamp

---

app/human-detector-app/App.tsx
app/human-detector-app/__tests__/BackendService.test.ts
app/human-detector-app/classes/Notification.ts
app/human-detector-app/classes/PushNotificationData.ts
app/human-detector-app/classes/User.tsx
app/human-detector-app/screens/CameraScreen.tsx
app/human-detector-app/screens/NotifScreen.tsx
app/human-detector-app/services/backendService.ts
app/human-detector-app/src/navigation/stackParamList.tsx

Made changes to the notification screen so that when a user is taken to that screen, non-serializable warnings wouldn't occur.  This was done by throwing camera ids to the notification screen since we're always gonna be getting all of a cameras notifications at the very least.  I also included small changes like long month printing on each notification.
Everything works as expected and the warnings don't pop up anymore.
https://eyespycamera.atlassian.net/jira/software/projects/EYE/boards/1?selectedIssue=EYE-105

[EYE-105] Fixed non-serializable bug

---

camera/auth/src/eyespy_service.py
package-lock.json

Only new behavior is to delete keys if the failure reason is `Incorrect_Secrets`. The last remaining failure reason is `NO_SSID`, but I made it explicit here to be clearer.

Delete wifi connection and internal keys on failure

---

app/human-detector-app/screens/CameraRegistration/BluetoothScreen.tsx
app/human-detector-app/src/ble/bleServices.ts

Super easy fix to EYE-120.  Had to call the setAllDevices hook in `stopScanForDevices` to update the value of the devices array on the screen.
Local testing with the pi I have, the device list is cleared now.
https://eyespycamera.atlassian.net/jira/software/projects/EYE/boards/1?selectedIssue=EYE-120

added callback to set devices for the screen

---

server/cdk/lib/cdk-stack.ts

Users who sign up in the app weren't being synchronized to our database, causing every backend request to reject with `403`. This hacky fix adds a post-confirmation trigger, reusing the sync lambda meant for a post-auth event.
Signing up in the app and adding/deleting groups works as expected now.

[EYE-134] Sync users to DB on sign-up

---

server/cdk/lib/cdk-stack.ts

Login with Google previously wasn't synchronizing to our DB, and login broke completely after adding email as a required attribute. This PR maps the email of Google users to Cognito's required `email` attribute, which fixes login. #80 seems to have also fixed the sync issues with Google login as well.
Signing in for the first time with my Google account worked, and I was able to create and delete groups as usual.

[EYE-141] Fix Google login
